### ISSUE TITLE
Anyway to sync clocks?

### ISSUE THREAD

**Issue by Spyindabox** [psmoveservice/PSMoveService#611]
https://hangyinuml.wordpress.com/2012/07/19/stereo-vision-grab-frames-with-opencv-2-x-ps3-eye/

At  this link the guy talks about  using ps3 eye cameras as a diy depth cameras by syncing frames? Is it  possible  to do this  via  just using the driver rather  than modding the actual hardware? Was hoping to use a ps3 eye camera for opencv stereo. Any help would be welcome.

**Comment by cboulay** [comment]
Sorry I didn't see anything at that link about syncing frames or calculating depth.

**Comment by Spyindabox** [comment]
Nevermind then I think, I misunderstood the article I thought he was doing realtime stereo syncing, which requires for the cameras to be synced. He was probably just syncing pictures.

**Comment by cboulay** [comment]
That links is a bit old, using older OpenCV APIs, and it relies on CLEye driver because PS3EYEDriver wasn't available on Windows at the time.

Anyway, we could do a better job of syncing cameras. Currently each camera is [grabbed and retrieved](https://github.com/psmoveservice/PSMoveService/blob/master/src/psmoveservice/PSMoveTracker/PS3EyeTracker.cpp#L387-L388) before moving on to the next camera.
We could [`grab`](https://docs.opencv.org/3.4.5/d8/dfe/classcv_1_1VideoCapture.html#ae38c2a053d39d6b20c9c649e08ff0146) all cameras first, and then retrieve from each one after (each in its own thread). This would likely help the multi-camera setups.

There are some other plans to improve tracking that could really leverage multi-threading, so we'll get the tracking algorithm implemented first then we'll separate the IMU updates and different tracker retrieving into separate threads.

**Comment by HipsterSloth** [comment]
@Spyindabox To add to what cboulay said, if you were interested in a stereo setup I was playing with that in my PSVRTracker testbed. 

https://github.com/HipsterSloth/PSVRTracker

Initially I had tried to get it working with two side by side PS3Eye cameras. Unfortunately it really on worked for stationary scene (the unsync'ed video frames threw off the disparity calculations). I eventually got a cheap true stereo camera 

https://www.amazon.com/ELP-Industrial-Application-Synchronized-ELP-960P2CAM-V90-VC/dp/B078TDLHCP

This camera works as a standard web camera and can be accessed through the windows media framework api. Here's a half decent disparity image I got using that camera:

![Disparity](https://user-images.githubusercontent.com/16793853/54178996-bd934e00-4454-11e9-9885-77ac20d883a9.jpg)

It took a while for me to figure out the right settings to use on OpenCV's stereo calibration functions that would yield reliably consistent results. Here's that tool if it's helpful:

https://github.com/HipsterSloth/PSVRTracker/blob/master/src/psvrconfigtool/AppStage_StereoCalibration.cpp

Once the PSVRTracker code is in a better place I'd like to merge the relevant parts back into PSMoveService. In the mean time feel free to pull anything from PSVRTracker if it's useful to you.
