### ISSUE TITLE
can i use a normal pc camera or does it have to be pseye

### ISSUE THREAD

**Issue by hello12568** [psmoveservice/PSMoveService#695]
please help

**Comment by AgoniXX** [comment]
Must be pseye. 
Or Driver4VR can use visual tracking or Kinect

**Comment by MuffinFalconAdmin** [comment]
fuck

**Comment by cboulay** [comment]
You can try uncommenting [these lines of code](https://github.com/psmoveservice/PSMoveService/blob/master/src/psmoveservice/PSMoveTracker/PSEye/PSEyeVideoCapture.cpp#L525-L529) and rebuilding psmoveservice from source. This will have psmoveservice fall back onto any opencv-supported camera that it can find. We chose not to support this because (a) generic webcams are poorly spec'd for this and (b) it makes it harder to debug what's wrong when the pseye is present but malfunctioning.
