### ISSUE TITLE
2021 - Still update ? - Roadmap of the project

### ISSUE THREAD

**Issue by gamersalpha** [psmoveservice/PSMoveService#752]
Hello, 
this one a project i really like

i need to know if u still support it and dev it 

or we can say is dead ?

thanks to u

**Comment by gamersalpha** [comment]
Hello there  

last release 

![image](https://user-images.githubusercontent.com/32466950/103686115-9ba27e00-4f8e-11eb-8bb9-10a7cd2c97c5.png)


and 4 commit since this release
guys please tell me is ot dead, is on of the best project on the internet !!!

**Comment by cboulay** [comment]
I'm honestly surprised there has been this much interest in the project because there are many good medium-cost VR solutions out there that are way better than using the PS Move controllers on PC.

I haven't made a release since the more recent commits because I haven't tested it. Setting up my computer with the hardware to test, and doing a thorough test, is more work than I have time for.

If others want to make pull requests then I'll review them and merge them if there isn't anything obviously nefarious, but I won't build and distribute binaries that I haven't vetted myself.

If you want to contribute, I just made a new issue that I think would be valuable:
https://github.com/psmoveservice/PSMoveService/issues/753

**Comment by gamersalpha** [comment]
Hello thanks for u response !

so that's means u will not update the project, expect someone can still continue to code it.

u maybe right i have to get a new hardware mlore easly to play with 

but i m really like play with psmove and psnavi,

that's a little sad for me, but is the life of all open project :'(

thanks for all u works, i really have good time with this project !

THanks

**Comment by endasil** [comment]
If you are having a registry issue when trying to pair a controller, it is fixed in the latest code, just not built by the author. If you check out my comment here https://github.com/psmoveservice/PSMoveService/issues/756 I provided a link to my build.
